car1:
  autonomy_manager:
    ros__parameters:
      cmd_bridge_input_topic: 'cmd/in'
      cmd_bridge_output_topic: 'cmd/out'
  steering_driver:
    ros__parameters:
      min_angle: -1.309
      max_angle: 1.309
  v2x_node:
    ros__parameters:
      car_state_output_topic: 'car_state'
      neighbor_list: ['car1', 'car2', 'car3', 'signal1']
      report_frequency: 1.0
      mqtt_broker_uri: '10.1.1.1'
  ackermann_controller:
    ros__parameters:
      ackermann_bridge_input_topic: 'ackermann/in'
      ackermann_bridge_output_topic: 'ackermann/out'
      twist_bridge_input_topic: 'twist/in'
      twist_bridge_output_topic: 'twist/out'
      vehicle_length: 0.24
      max_velocity: 2.64
      min_velocity: 0.01
      min_omega: 0.01
  straight_behavior:
    ros__parameters:
      velocity: 0.75
      twist_topic: 'twist/in'
  arc_behavior:
    ros__parameters:
      velocity: 0.75
      steering_angle: 0.45
      twist_topic: 'twist/in'
  bno055_driver:
    ros__parameters:
      imu_topic: "example/imu"
      imu_rate: 5.0
